[package]
name = "mangodb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = {version = "2.8.1", features = ["tokio-runtime"] }
tokio = { version = "1.36.0", features = ["full"] }
